#!/usr/bin/env bash

pushd /Users/robert/projects/typescript/impftermin-brandenburg/;

if [[ -d puppeteer-user-data-dir ]]; then
    rm -rf puppeteer-user-data-dir/
fi

npm run run

rm -rf puppeteer-user-data-dir/
